title: Robert J. Carroll
logo: ikb-big.png
description: Website for Robert J. Carroll, a political scientist at the University of Illinois at Urbana-Champaign
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
