title: Rob Carroll
logo: /assets/img/logo.png
description: Website for Rob Carroll, a political scientist at the University of Illinois at Urbana-Champaign
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
